### ISSUE TITLE
Login and password for Pixelhue P10, P20 and Q8

### ISSUE THREAD

**Issue by bscav** [bitfocus/companion-module-pixelhue-switcher#2]
Hello,

Please add the login and password for those switchers as default or at least add them in the help section. As far as I know as a user you can't change login and password for the switcher. That's way making it a secret that you need to get from a Pixelhue employee is an unnecessary gatekeeping.

Here are the login and password:

User: admin
Password: MTIzNDU2

**Comment by novastarQQ** [comment]
In the new version, we designed the device connection to login without password.
I will close this issue in a week.
